[package]
name = "des"
version = "0.1.0"
authors = ["crypto-universe <ykp@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = { path = "bindings" }
windows = "0.21.1"
utf16_lit = "2.0.2"