#[allow(non_camel_case_types)]
#[allow(clippy::upper_case_acronyms)]
#[derive(PartialOrd, PartialEq, Ord, Eq, Clone, Copy, FromPrimitive)]
pub enum MenuId {
    GUEST = 1,
    GUEST_VIRTUALBOX,
    GUEST_VMWARE,
    GUEST_PARALLELS,
    GUEST_HYPERV,
    GUEST_VIRTUAL_PC,
    DEBUGGER,
    DEBUGGER_OLLY,
    DEBUGGER_WINDBG,
    DEBUGGER_X64DBG,
    DEBUGGER_IDA,
    DEBUGGER_IMMUNITY,
    DEBUGGER_RADARE2,
    DEBUGGER_BINARY_NINJA,
    ANTIVIRUS,
    // ANTIVIRUS_AVAST,
    ANTIVIRUS_AVIRA,
    // ANTIVIRUS_BITDEFENDER,
    // ANTIVIRUS_DRWEB,
    ANTIVIRUS_ESCAN,
    // ANTIVIRUS_ESET_NOD32,
    ANTIVIRUS_FORTINET,
    // ANTIVIRUS_FSECURE,
    ANTIVIRUS_GDATA,
    ANTIVIRUS_K7,
    // ANTIVIRUS_KASPERSKY,
    // ANTIVIRUS_MALWAREBYTES,
    ANTIVIRUS_MCAFEE,
    // ANTIVIRUS_NORTON,
    // ANTIVIRUS_PANDA,
    // ANTIVIRUS_SOPHOS,
    // ANTIVIRUS_TREND_MICRO,
    // ANTIVIRUS_WEBROOT,
    // FIREWALL,
    // FIREWALL_ZONEALARM,
    // FIREWALL_GLASSWIRE,
    // FIREWALL_COMODO,
    // FIREWALL_TINYWALL,

    TOOLS,
    TOOLS_PEID,
    TOOLS_RESOURCE_HACKER,
    TOOLS_DIE,
    TOOLS_DEBUG_VIEW,
    TOOLS_PROCESS_MONITOR,
    TOOLS_PROCESS_EXPLORER,
    TOOLS_TCPVIEW,
    TOOLS_WIRESHARK,
    TOOLS_PE_TOOLS,
    TOOLS_SPYXX,
    TOOLS_CTK_RES_EDIT,
    TOOLS_XN_RES_EDITOR,
    // CFF explorer
    // API monitor
    // WinHex
    // HxD
    // Hiew
    // Fiddler
    // Scylla
    // Ghidra

    ABOUT,
    EXIT,
    PAUSE,
    RESUME,
}
